---
title: "Chapter 6"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(lmerTest)
library(rethinking)
library(tidyverse)

# bogus data
data(Howell1)
d <- Howell1
d$age <- (d$age - mean(d$age))/sd(d$age)
set.seed( 1000 )

# train-test
i <- sample(1:nrow(d),size=nrow(d)/2)
d1 <- d[ i , ]
d2 <- d[ -i , ]
```

#6H1. 
```{r}
mean(d1$height)
#centering(d1$height)
#d1$age_scale <- scale(d1$age)

m1 <- rethinking::map(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- alpha + b1*age,
    alpha ~ dnorm(140, 20),
    b1 ~ dnorm(0, 50),
    sigma ~ dnorm(0, 20)
  ), data = d1,
method="Nelder-Mead" ,
control=list(maxit=1e4))


m2 <- rethinking::map(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- alpha + b1*age + b2*age^2,
    alpha ~ dnorm(140, 20),
    b1 ~ dnorm(0, 50),
    b2 ~ dnorm(0, 10),
    sigma ~ dnorm(0, 20)
  ), data = d1,
  method="Nelder-Mead" ,
control=list(maxit=1e4))

m3 <- rethinking::map(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- alpha + b1*age + b2*age^2 + b3*age^3,
    alpha ~ dnorm(140, 20),
    b1 ~ dnorm(0, 50),
    b2 ~ dnorm(0, 10),
    b3 ~ dnorm(0, 10),
    sigma ~ dnorm(0, 20)
  ), data = d1,
  method="Nelder-Mead" ,
control=list(maxit=1e4))

m4 <- rethinking::map(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- alpha + b1*age + b2*age^2 + b3*age^3 + b4*age^4,
    alpha ~ dnorm(140, 20),
    b1 ~ dnorm(0, 50),
    b2 ~ dnorm(0, 10),
    b3 ~ dnorm(0, 10),
    b4 ~ dnorm(0, 5),
    sigma ~ dnorm(0, 20)
  ), data = d1,
  method="Nelder-Mead" ,
control=list(maxit=1e4))

m5 <- rethinking::map(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- alpha + b1*age + b2*age^2 + b3*age^3 + b4*age^4 + b5*age^5,
    alpha ~ dnorm(140, 20),
    b1 ~ dnorm(0, 50),
    b2 ~ dnorm(0, 10),
    b3 ~ dnorm(0, 10),
    b4 ~ dnorm(0, 5),
    b5 ~ dnorm(0, 5),
    sigma ~ dnorm(0, 20)
  ), data = d1,
  method="Nelder-Mead" ,
control=list(maxit=1e4))

m6 <- rethinking::map(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- alpha + b1*age + b2*age^2 + b3*age^3 + b4*age^4 + b5*age^5 + b6*age^6,
    alpha ~ dnorm(140, 20),
    b1 ~ dnorm(0, 50),
    b2 ~ dnorm(0, 10),
    b3 ~ dnorm(0, 10),
    b4 ~ dnorm(0, 5),
    b5 ~ dnorm(0, 5),
    b6 ~ dnorm(0, 5),
    sigma ~ dnorm(0, 20)
  ), data = d1,
  method="Nelder-Mead" ,
control=list(maxit=1e4))


precis(m1)
precis(m2)
precis(m3)
precis(m4)
precis(m5)
precis(m6)
comparisons <- compare(m1, m2, m3, m4, m5, m6)
```

#6H2

model1
```{r}

age.seq <- seq(from = -3, to = 3, by = 0.1)
sim.age <- sim(m1, data = list(age = age.seq))
height.PI <- apply(sim.age, 2, PI, prob = 0.97)
mu <- link(m1)
mu <- link(m1, data = data.frame(age = age.seq))
mu.mean <- apply(mu, 2, mean) 
mu.HPDI <- apply(mu, 2, HPDI, prob = 0.97)

plot(height ~ age, d1, col = col.alpha(rangi2, 1))
lines(age.seq, mu.mean)
# draw HPDI region for line
shade(mu.HPDI, age.seq )
# draw PI region for simulated heights
shade(height.PI, age.seq ) 

```

model2 

```{r}
age.seq <- seq(from = -3, to = 3, by = 0.1)
sim.age <- sim(m2, data = list(age = age.seq))
height.PI <- apply(sim.age, 2, PI, prob = 0.97)
mu <- link(m2)
mu <- link(m2, data = data.frame(age = age.seq))
mu.mean <- apply(mu, 2, mean) 
mu.HPDI <- apply(mu, 2, HPDI, prob = 0.97)

plot(height ~ age + age ^2 , d1, col = col.alpha(rangi2, 1))
lines(age.seq, mu.mean)
# draw HPDI region for line
shade(mu.HPDI, age.seq )
# draw PI region for simulated heights
shade(height.PI, age.seq ) 
```

model3

```{r}
age.seq <- seq(from = -3, to = 3, by = 0.1)
sim.age <- sim(m3, data = list(age = age.seq))
height.PI <- apply(sim.age, 2, PI, prob = 0.97)
mu <- link(m3)
mu <- link(m3, data = data.frame(age = age.seq))
mu.mean <- apply(mu, 2, mean) 
mu.HPDI <- apply(mu, 2, HPDI, prob = 0.97)

plot(height ~ age + age ^2 , d1, col = col.alpha(rangi2, 1))
lines(age.seq, mu.mean)
# draw HPDI region for line
shade(mu.HPDI, age.seq )
# draw PI region for simulated heights
shade(height.PI, age.seq ) 
```

model4

```{r}
age.seq <- seq(from = -3, to = 3, by = 0.1)
sim.age <- sim(m4, data = list(age = age.seq))
height.PI <- apply(sim.age, 2, PI, prob = 0.97)
mu <- link(m4)
mu <- link(m4, data = data.frame(age = age.seq))
mu.mean <- apply(mu, 2, mean) 
mu.HPDI <- apply(mu, 2, HPDI, prob = 0.97)

plot(height ~ age + age ^2 , d1, col = col.alpha(rangi2, 1))
lines(age.seq, mu.mean)
# draw HPDI region for line
shade(mu.HPDI, age.seq )
# draw PI region for simulated heights
shade(height.PI, age.seq ) 
```


model5

```{r}
age.seq <- seq(from = -3, to = 3, by = 0.1)
sim.age <- sim(m5, data = list(age = age.seq))
height.PI <- apply(sim.age, 2, PI, prob = 0.97)
mu <- link(m5)
mu <- link(m5, data = data.frame(age = age.seq))
mu.mean <- apply(mu, 2, mean) 
mu.HPDI <- apply(mu, 2, HPDI, prob = 0.97)

plot(height ~ age + age ^2 , d1, col = col.alpha(rangi2, 1))
lines(age.seq, mu.mean)
# draw HPDI region for line
shade(mu.HPDI, age.seq )
# draw PI region for simulated heights
shade(height.PI, age.seq ) 
```

model6

```{r}
age.seq <- seq(from = -3, to = 3, by = 0.1)
sim.age <- sim(m6, data = list(age = age.seq))
height.PI <- apply(sim.age, 2, PI, prob = 0.97)
mu <- link(m6)
mu <- link(m6, data = data.frame(age = age.seq))
mu.mean <- apply(mu, 2, mean) 
mu.HPDI <- apply(mu, 2, HPDI, prob = 0.97)

plot(height ~ age + age ^2 , d1, col = col.alpha(rangi2, 1))
lines(age.seq, mu.mean)
# draw HPDI region for line
shade(mu.HPDI, age.seq )
# draw PI region for simulated heights
shade(height.PI, age.seq ) 
```


#6H3
```{r}
age.seq <- seq(from=-3,to=3,length.out=30)
age.predict <- list(
height = rep(0,30), # empty outcome
age = age.seq #average of verbal
)

pred.m1 <- link( m1 , data=age.predict )
mu <- apply( pred.m1 , 2 , mean )
mu.PI <- apply( pred.m1 , 2 , PI )

plot( height ~ age , d1 , col=rangi2 )

#ensemble
age.ensemble <- ensemble(m1, m2, m3, m4, m5, m6, data = age.predict)
mu <- apply( age.ensemble$link , 2 , mean )
mu.PI <- apply( age.ensemble$link , 2 , PI )
lines( age.seq , mu )
shade( mu.PI , age.seq )
```
